apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "foo.labels" }}
data:
  myvalue: "Hello world"
  {{- range $key, $value := .Values.favorite }}
  {{ $key }}: {{ $value }}
  {{- end }}
