# Default values for nfs-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: node2
namespace: ""
image:
  repository: erichough/nfs-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.2.1"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: { privileged: true }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports:
  nfs: 2049
  rpcbind: 111 
  mountd: 32767
  statd: 32765




