apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello world"
  drink: {{  .Values.favorite.drink | default "tea" | quote }}
  {{- if eq .Values.favorite.drink "coffee"  }}
  mug: true 
  {{- end }}
  food: {{ .Values.favorite.food | upper | quote -}} 
