apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteMany
 # persistentVolumeReclaimPolicy: Delete
  nfs: 
    server: 10.100.165.105
    path: "/nfs-export"
