apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs-client.fullname"  . }}
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Mi
       
