apiVersion: v1
kind: Pod
metadata:
  name: {{ printf "%s-update-content" ( include "nfs-client.fullname" . )  }}
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep 10; done']
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nfs
        mountPath: "/mnt"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: {{  include "nfs-client.fullname" . }}
