apiVersion: v1
kind: Pod
metadata:
  name: {{ printf "%s-web-server" ( include "nfs-client.fullname" . ) }}
  labels:
    {{- include "nfs-client.labels" . | nindent 4  }}
spec:
  containers:
    - name: web-sever
      image: nginx
      ports:
      - name: web
        containerPort: 80
      volumeMounts:
       - name: nfs
         mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: {{ include "nfs-client.fullname" . }}

