{{- define "foo.labels" -}}
  labels:
    generator: helm
    date: {{ now | htmlDate }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  {{ template "foo.labels"  }}
data:
   animal: dog
