
{{- define "foo.extraLabels" -}}
fullName: {{ .Release.Name }}-Yoav
version: "1.23"
{{- end }}

{{- define "foo.labels" -}}
labels:
  start: first
  {{- include "foo.extraLabels" . | nindent 2 }}
  end: last
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- include  "foo.labels"  . | nindent 2}}
data:
   animal: dog
