{{- define "foo.extraLabels" -}}
version: "v1"
app: "myapp"
{{- end }}

{{- define "foo.labels" -}}
  labels:
    generator: helm
    {{- include  "foo.extraLabels" . | nindent 4 }}
    date: {{ now | htmlDate }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  {{ template "foo.labels"  }}
data:
   animal: dog
