{{- define "foo.extraLabels" -}}
version: "v1"
app: "myapp"
{{- end }}

{{- define "foo.labels" -}}
labels:
  generator: helm
  {{- include  "foo.extraLabels" . | nindent 2 }}
  date: {{ now | htmlDate }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  {{- include "foo.labels" . | nindent 2 }}
data:
   animal: dog
