apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  nfs: 
    server: 10.111.142.120
    path: "/nfs-export"
