apiVersion: v1
kind: Pod
metadata:
  name: nfs-server  # {{ include "nfs-server.fullname" . }}
  labels:
     {{- include "nfs-server.labels" . | nindent 6 }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  nodeName: {{ .Values.nodeName }}
  containers:
  - name: nfs-server
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    ports:
    - name: nfs
      containerPort: {{ .Values.ports.nfs }}
    - name: rpcbind
      containerPort: {{ .Values.ports.rpcbind }}
    - name: statd
      containerPort: {{ .Values.ports.statd }}
    - name: mountd
      containerPort: {{ .Values.ports.mountd }}
    securityContext:
       {{- toYaml .Values.securityContext | nindent 6 }}
    env:
    - name: NFS_EXPORT_0
      value: '/nfs-export *(rw,no_subtree_check)'
    volumeMounts:
    - name: export
      mountPath: '/nfs-export'
  volumes:
  - name: export
    hostPath:
      path: '/mnt/nfs-export'
